- regExp: "packages\/electron(\/.*)?$"
  labels: ["electron"]
- regExp: "packages\/alphachart(\/.*)?$"
  labels: ["alphachart"]
- regExp: "packages\/alphachart-guest(\/.*)?$"
  labels: ["alphachart-guest"]
- regExp: "packages\/desktop(\/.*)?$"
  labels: ["desktop"]
- regExp: "packages\/mobile(\/.*)?$"
  labels: ["mobile"]
- regExp: "^packages\/[^\/]+(\/.*)?$|^([^\/]+)?$"
  labels: ["desktop", "mobile"]
