electron:
  - all: ["packages/electron/**/*"]
alphachart:
  - all: ["packages/alphachart/**/*"]
alphachart-guest:
  - all: ["packages/alphachart-guest/**/*"]
desktop:
  - all: ["packages/desktop/**/*"]
mobile:
  - all: ["packages/mobile/**/*"]
