# - regExp: "packages\/electron(\/.*)?$"
#   labels: ["electron"]
# - regExp: "packages\/alphachart(\/.*)?$"
#   labels: ["alphachart"]
# - regExp: "packages\/alphachart-guest(\/.*)?$"
#   labels: ["alphachart-guest"]
# - regExp: "packages\/desktop(\/.*)?$"
#   labels: ["desktop"]
# - regExp: "packages\/mobile(\/.*)?$"
#   labels: ["mobile"]
# - regExp: "^packages\/[^\/]+(\/.*)?$|^([^\/]+)?$"
#   labels: ["desktop", "mobile"]
electron: ["packages\/electron(\/.*)?$"]
alphachart: ["packages\/alphachart(\/.*)?$"]
alphachart-guest: ["packages\/alphachart-guest(\/.*)?$"]
desktop:
  - "packages/desktop/**/*"
  - "*/**"
mobile:
  - "packages/mobile/**/*"
  - "*/**"
