name: PR Release Labeler
on:
  pull_request_review:
    types: [submitted]

jobs:
  triage:
    if: github.event.review.state == 'approved'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/pr-release-labeler.yml
          sync-labels: true
