name: Release Drafter

on:
  pull_request:
    types: [closed]

jobs:
  desktop-draft-release:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && (contains(github.event.pull_request.labels.*.name, 'desktop') || join(github.event.issue.labels) == '')
    steps:
      - name: Release drafter
        echo "Release desktop"

  mobile-draft-release:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && (contains(github.event.pull_request.labels.*.name, 'mobile') || join(github.event.issue.labels) == '')
    steps:
      - name: Release drafter
        echo "Release mobile"
  alphachart-draft-release:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && contains(github.event.pull_request.labels.*.name, 'alphachart')
    steps:
      - name: Release drafter
        echo "Release alphachart"

  alphachart-guest-draft-release:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && contains(github.event.pull_request.labels.*.name, 'alphachart-guest')
    steps:
      - name: Release drafter
        echo "Release alphachart-guest"